CREATE TABLE [dbo].[FeePayment]
(
 FeePaymentId BIGINT IDENTITY(1, 1), 
 AcademicYearId SMALLINT,
 GradeId SMALLINT,
 DivisionId SMALLINT,
 StudentId BIGINT,
 InvoiceNumber VARCHAR(100),
 OnlineTransactionId VARCHAR(300),
 OnlineTransactionDateTime DATETIME, 
 OnlinePaymentRequest VARCHAR(1000), 
 OnlinePaymentResponse VARCHAR(1000), 
 PaidToBank NVARCHAR(100), 
 PaidAmount MONEY,
 PaymentTypeId SMALLINT,
 ChequeNumber NVARCHAR(100), 
 ChequeDate DATETIME, 
 ChequeBank NVARCHAR(100), 
 ChequeAmount MONEY,
 IsChequeClear BIT DEFAULT(0) NOT NULL,
 Remark NVARCHAR(100), 
 SkipDiscount BIT DEFAULT(0) NOT NULL,
 FeeWavierTypesInstallmentsDetailsId BIGINT,
 CreatedBy INT, 
 CreatedDate DATETIME, 
 ModifiedBy INT, 
 ModifiedDate DATETIME, 
 IsDeleted BIT DEFAULT(0) NOT NULL,
 CONSTRAINT [PKFeePayment] PRIMARY KEY CLUSTERED ([FeePaymentId] ASC),
 CONSTRAINT [FKFeePaymentAcademicYear] FOREIGN KEY (AcademicYearId) REFERENCES AcademicYear(AcademicYearId),
 CONSTRAINT [FKFeePaymentStudent] FOREIGN KEY (StudentId) REFERENCES Student(StudentId),
 CONSTRAINT [FKFeePaymentFeeWavierTypesInstallmentsDetails] FOREIGN KEY (FeeWavierTypesInstallmentsDetailsId) REFERENCES FeeWavierTypesInstallmentsDetails(FeeWavierTypesInstallmentsDetailsId),

             
)