CREATE TABLE Parent(
  ParentId BIGINT IDENTITY(1, 1), 
  ParentTypeId SMALLINT, 
  FirstName NVARCHAR(50), 
  MiddleName NVARCHAR(50), 
  LastName NVARCHAR(50), 
  Gender NVARCHAR(5), 
  ContactNumber NVARCHAR(20), 
  MobileNumber NVARCHAR(20), 
  EmailId VARCHAR(80), 
  AddressLine1 NVARCHAR(250), 
  AddressLine2 NVARCHAR(250), 
  TalukaId INT, 
  DistrictId INT, 
  StateId INT, 
  CountryId INT, 
  TalukaName NVARCHAR(100), 
  DistrictName NVARCHAR(100), 
  StateName NVARCHAR(100), 
  CountryName NVARCHAR(100), 
  Zipcode NVARCHAR(10), 
  AdharNumber NVARCHAR(20), 
  Education NVARCHAR(50), 
  BirthDate DATE, 
  Occupation NVARCHAR(50), 
  AnnualIncome MONEY, 
  BloodGroup NVARCHAR(5), 
  ProfileImageURL VARCHAR(100), 
  CreatedBy INT, 
  CreatedDate DATETIME, 
  ModifiedBy INT, 
  ModifiedDate DATETIME, 
  IsDeleted BIT DEFAULT(0) NOT NULL,
  CONSTRAINT [PKParent] PRIMARY KEY CLUSTERED ([ParentId] ASC)
);

