CREATE TABLE School (
  SchoolId SMALLINT IDENTITY (1, 1), 
  SchoolName NVARCHAR(500), 
  SchoolCode NVARCHAR(15), 
  SchoolCodeNo NVARCHAR(100), 
  SchoolEmail VARCHAR(80), 
  SchoolContactNo1 NVARCHAR(20), 
  SchoolContactNo2 NVARCHAR(20), 
  SchoolAddressLine1 NVARCHAR(250), 
  SchoolAddressLine2 NVARCHAR(250), 
  TalukaId INT, 
  DistrictId INT, 
  StateId INT, 
  CountryId INT, 
  TalukaName NVARCHAR(100), 
  DistrictName NVARCHAR(100), 
  StateName NVARCHAR(100), 
  CountryName NVARCHAR(100), 
  Pincode NVARCHAR(10), 
  EstablishmentDate DATE, 
  SchoolRank NVARCHAR(250), 
  SchoolWebsiteUrl NVARCHAR(250), 
  LogoUrl VARCHAR(100), 
  BannerUrl VARCHAR(100), 
  SchoolDescription NVARCHAR(500), 
  ContactPersonName NVARCHAR(50), 
  ContactPersonRole NVARCHAR(50), 
  ContactPersonEmail VARCHAR(80), 
  ContactPersonMobileNo NVARCHAR(20), 
  AcademicYearId SMALLINT, 
  InvoiceNoPrefix NVARCHAR(20),
  InvoiceNoStartNumber INT,
  TransportInvoiceNoPrefix NVARCHAR(20),
  TransportInvoiceNoStartNumber INT,
  AdditionalFeeInvoiceNoPrefix NVARCHAR(20),
  AdditionalFeeInvoiceNoStartNumber INT,
  SchoolKitInvoiceNoPrefix NVARCHAR(20),
  SchoolKitInvoiceNoStartNumber INT,
  RegistrationFeeInvoiceNoPrefix NVARCHAR(20),
  RegistrationFeeInvoiceNoStartNumber INT,
  SerialNoStartNumber INT,
  AuthorisedBy NVARCHAR(500), 
  Section NVARCHAR(500), 
  SchoolMediumId SMALLINT, 
  SchoolPermission NVARCHAR(500), 
  RegistrationNumber NVARCHAR(500), 
  SchoolType NVARCHAR(200), 
  UdiseNumber NVARCHAR(500), 
  Board NVARCHAR(500), 
  AffiliationNumber NVARCHAR(500), 
  HscOrSscIndexNo NVARCHAR(200), 
  AccountNumber NVARCHAR(50),
  AccountTypeId INT,
  IFSCCode NVARCHAR(50),
  AccountName NVARCHAR(150),
  LangaugeCode NVARCHAR(150),
  SchoolLat NVARCHAR(200),
  SchoolLng NVARCHAR(200),
  CreatedBy INT, 
  CreatedDate DATETIME, 
  ModifiedBy INT, 
  ModifiedDate DATETIME, 
  IsDeleted BIT DEFAULT(0) NOT NULL,
  CONSTRAINT [PKSchool] PRIMARY KEY CLUSTERED ([SchoolId] ASC),
  CONSTRAINT [FKSchoolAcademicYear] FOREIGN KEY (AcademicYearId) REFERENCES AcademicYear(AcademicYearId)
);
