CREATE TABLE StudentGradeDivisionMapping (
  StudentGradeDivisionMappingId BIGINT IDENTITY(1, 1), 
  StudentId BIGINT, 
  AcademicYearId SMALLINT,
  IsPassed BIT,
  GradeId SMALLINT, 
  DivisionId SMALLINT, 
  PromotedAcademicYearId SMALLINT,
  PromotedGradeId SMALLINT, 
  PromotedDivisionId SMALLINT, 
  RollNumber NVARCHAR(20), 
  IsRTEStudent BIT DEFAULT(0) NOT NULL, 
  IsConsationApplicable BIT DEFAULT(0) NOT NULL, 
  ConsationAmount MONEY, 
  CreatedBy INT, 
  CreatedDate DATETIME, 
  ModifiedBy INT, 
  ModifiedDate DATETIME, 
  IsDeleted BIT DEFAULT(0) NOT NULL,
  CONSTRAINT [PKStudentGradeDivisionMapping] PRIMARY KEY CLUSTERED ([StudentGradeDivisionMappingId] ASC),
  CONSTRAINT [FKStudentGradeDivisionMappingStudent] FOREIGN KEY (StudentId) REFERENCES Student(StudentId),
  CONSTRAINT [FKStudentGradeDivisionMappingAcademicYear] FOREIGN KEY (AcademicYearId) REFERENCES AcademicYear(AcademicYearId),
  CONSTRAINT [FKStudentGradeDivisionMappingGrade] FOREIGN KEY (GradeId) REFERENCES Grade(GradeId),
  CONSTRAINT [FKStudentGradeDivisionMappingDivision] FOREIGN KEY (DivisionId) REFERENCES Division(DivisionId),
  CONSTRAINT [FKStudentGradeDivisionMappingPromotedAcademicYear] FOREIGN KEY (PromotedAcademicYearId) REFERENCES AcademicYear(AcademicYearId),
  CONSTRAINT [FKStudentGradeDivisionMappingPromotedGrade] FOREIGN KEY (PromotedGradeId) REFERENCES Grade(GradeId),
  CONSTRAINT [FKStudentGradeDivisionMappingPromotedDivision] FOREIGN KEY (PromotedDivisionId) REFERENCES Division(DivisionId),
);