CREATE TABLE Student(
  StudentId BIGINT IDENTITY(1, 1), 
  GeneralRegistrationNo NVARCHAR(100), 
  CbscStudentId NVARCHAR(50), 
  AdmissionNo NVARCHAR(100), 
  SchoolId SMALLINT, 
  FirstName NVARCHAR(50), 
  MiddleName NVARCHAR(50), 
  LastName NVARCHAR(50), 
  Gender NVARCHAR(5), 
  AdharNo NVARCHAR(20), 
  Religion NVARCHAR(50), 
  Category NVARCHAR(50), 
  Cast NVARCHAR(50), 
  SubCast NVARCHAR(50), 
  Nationality NVARCHAR(50), 
  MotherTounge NVARCHAR(50), 
  EmergencyContactPersonName NVARCHAR(100), 
  EmergencyContactNumber NVARCHAR(20), 
  FamilyDoctorName NVARCHAR(100), 
  FamilyDoctorContactNumber NVARCHAR(20), 
  BirthPlace NVARCHAR(100), 
  BirthDate DATE, 
  BirthDateInWords NVARCHAR(200), 
  BirthCountryId INT, 
  BirthStateId INT, 
  BirthDistrictId INT, 
  BirthTalukaId INT,
  BirthTalukaName NVARCHAR(100), 
  BirthDistrictName NVARCHAR(100), 
  BirthStateName NVARCHAR(100), 
  BirthCountryName NVARCHAR(100),
  CurrentAddressLine1 NVARCHAR (250),
  CurrentAddressLine2 NVARCHAR (250), 
  CurrentTalukaId INT, 
  CurrentDistrictId INT, 
  CurrentCountryId INT,
  CurrentStateId INT, 
  CurrentTalukaName NVARCHAR(100), 
  CurrentDistrictName NVARCHAR(100), 
  CurrentStateName NVARCHAR(100), 
  CurrentCountryName NVARCHAR(100),
  CurrentZipcode  NVARCHAR(10),
  BloodGroup NVARCHAR(5), 
  Height NVARCHAR(10), 
  Weight NVARCHAR(10), 
  MedicalHistory NVARCHAR(500), 
  AdmissionGrade NVARCHAR(10), 
  DateOfAdmission DATE, 
  LastSchoolAttended NVARCHAR(500), 
  LastSchoolStandard NVARCHAR(10), 
  LastSchoolDivision NVARCHAR(10), 
  ProgressNoteFromLastSchool NVARCHAR(500), 
  ConductNoteFromLastSchool NVARCHAR(500), 
  StandardInWhichLastStudyingSection NVARCHAR(50), 
  SinceWhenStudyingInLastSchool NVARCHAR(50), 
  ReasonOfLeavingSchoolLastSchool NVARCHAR(500), 
  DateOfLeavingLastSchool DATE, 
  RemarkFromLastSchool NVARCHAR(500), 
  IsNewStudent BIT DEFAULT(1) NOT NULL, 
  ProfileImageURL VARCHAR(100), 
  IsAppAccess BIT DEFAULT(0) NOT NULL,
  AppAccessMobileNo VARCHAR(20),
  AppAccessOneTimePassword NVARCHAR(100),
  IsArchive BIT DEFAULT(0) NOT NULL, 
  PreviousAcademicYearPendingFeeAmount MONEY,
  GradeNameAdmission NVARCHAR(50),
  CreatedBy INT, 
  CreatedDate DATETIME, 
  ModifiedBy INT, 
  ModifiedDate DATETIME, 
  IsDeleted BIT DEFAULT(0) NOT NULL, 
  QRCode NVARCHAR(100)
  CONSTRAINT [PKStudent] PRIMARY KEY CLUSTERED ([StudentId] ASC),
  CONSTRAINT [FKStudentSchool] FOREIGN KEY (SchoolId) REFERENCES School(SchoolId)
  );
