CREATE TABLE Teacher (
  TeacherId BIGINT IDENTITY (1, 1) NOT NULL, 
  FirstName NVARCHAR(50), 
  MiddleName NVARCHAR (50), 
  LastName NVARCHAR (50), 
  Gender NVARCHAR (5), 
  ContactNumber NVARCHAR(20), 
  MobileNumber NVARCHAR(20), 
  EmailId VARCHAR(80), 
  AddressLine1 NVARCHAR(250), 
  AddressLine2 NVARCHAR (250), 
  TalukaId INT, 
  DistrictId INT, 
  StateId INT, 
  TalukaName NVARCHAR(100), 
  DistrictName NVARCHAR(100), 
  StateName NVARCHAR(100), 
  CountryName NVARCHAR(100), 
  AdharNumber NVARCHAR (20), 
  CountryId INT, 
  ZipCode NVARCHAR (10), 
  Education NVARCHAR (50), 
  BirthDate DATE, 
  BloodGroup NVARCHAR (5), 
  ProfileImageUrl VARCHAR(100), 
  IsAppAccess BIT DEFAULT(0) NOT NULL,
  AppAccessMobileNo VARCHAR(20),
  AppAccessOneTimePassword NVARCHAR(100),
  CreatedBy INT, 
  CreatedDate DATETIME, 
  ModifiedBy INT, 
  ModifiedDate DATETIME, 
  [IsDeleted] BIT DEFAULT(0) NOT NULL,
  CONSTRAINT [PKTeacher] PRIMARY KEY CLUSTERED ([TeacherId] ASC)
);

