CREATE TABLE [dbo].[TransportFeePayment]
(
 TransportFeePaymentId BIGINT IDENTITY(1, 1), 
 AcademicYearId SMALLINT,
 ConsumerId BIGINT,
 TransportConsumerStoppageMappingId INT,
 RoleId INT,
 InvoiceNumber VARCHAR(100),
 OnlineTransactionId VARCHAR(300),
 OnlineTransactionDateTime DATETIME, 
 OnlinePaymentRequest VARCHAR(1000), 
 OnlinePaymentResponse VARCHAR(1000), 
 PaidToBank NVARCHAR(100), 
 PaidAmount MONEY,
 PaymentTypeId SMALLINT,
 ChequeNumber NVARCHAR(100), 
 ChequeDate DATETIME, 
 ChequeBank NVARCHAR(100), 
 ChequeAmount MONEY,
 IsChequeClear BIT DEFAULT(0) NOT NULL,
 Remark NVARCHAR(100), 
 MonthMasterId SMALLINT,
 CreatedBy INT, 
 CreatedDate DATETIME, 
 ModifiedBy INT, 
 ModifiedDate DATETIME, 
 IsDeleted BIT DEFAULT(0) NOT NULL,
 CONSTRAINT [PKTransportFeePayment] PRIMARY KEY CLUSTERED ([TransportFeePaymentId] ASC),
 CONSTRAINT [FKTransportFeePaymentAcademicYear] FOREIGN KEY (AcademicYearId) REFERENCES AcademicYear(AcademicYearId),
 CONSTRAINT [FKTransportFeePaymentRole] FOREIGN KEY (RoleId) REFERENCES Role(RoleId),
 CONSTRAINT [FKTransportFeePaymentTransportConsumerStoppageMapping] FOREIGN KEY (TransportConsumerStoppageMappingId) REFERENCES TransportConsumerStoppageMapping(TransportConsumerStoppageMappingId),
 CONSTRAINT [FKTransportFeePaymentMonthMaster] FOREIGN KEY (MonthMasterId) REFERENCES MonthMaster(MonthMasterId),

             
)