CREATE TYPE [dbo].[StudentImportType] AS TABLE
(
  CBSC_Student_Id NVARCHAR(50),
  Gen_Reg_No NVARCHAR(100), 
  Admission_No NVARCHAR(100), 
  Roll_No NVARCHAR(100),
  Grade NVARCHAR(10),
  Division NVARCHAR(10),
  Admission_Date DATETIME  NULL, 
  Student_First_Name NVARCHAR(50), 
  Student_Middle_Name NVARCHAR(50), 
  Student_Last_Name NVARCHAR(50), 
  Gender NVARCHAR(5), 
  Adhaar_No NVARCHAR(20), 
  Religion NVARCHAR(50), 
  Category NVARCHAR(50), 
  Cast NVARCHAR(50), 
  Sub_Caste NVARCHAR(50), 
  Nationality NVARCHAR(50), 
  Mother_Tongue NVARCHAR(50), 
  Emergency_Contact_Person_Name NVARCHAR(100), 
  Emergency_Contact_No NVARCHAR(20), 
  Family_Doctor_Name NVARCHAR(100), 
  Family_Doctor_No NVARCHAR(20), 
  Birth_Place NVARCHAR(100), 
  BirthDate DATETIME  NULL,  
  Date_Of_Birth_In_Words NVARCHAR(200), 
  Birth_Country NVARCHAR(100), 
  Birth_State NVARCHAR(100), 
  Birth_District NVARCHAR(100), 
  Birth_Taluka NVARCHAR(100),
  Current_Address_Line_1 NVARCHAR (250),
  Current_Address_Line_2 NVARCHAR (250), 
  Current_Pincode  NVARCHAR(10),
  Current_Country NVARCHAR(100), 
  Current_State NVARCHAR(100), 
  Current_District NVARCHAR(100), 
  Current_Taluka NVARCHAR(100),
  Blood_Group NVARCHAR(5), 
  Height NVARCHAR(10), 
  Weight NVARCHAR(10), 
  Medical_History_Notes NVARCHAR(500), 
  Previous_School_Name NVARCHAR(500), 
  Previous_School_Standard NVARCHAR(10), 
  Previous_School_Division NVARCHAR(10), 
  Progress_Note_From_Last_School NVARCHAR(500), 
  Conduct_Note_From_Last_School NVARCHAR(500), 
  Reason_of_Leaving_School NVARCHAR(500), 
  Date_of_Leaving_of_Previous_School DATETIME  NULL, 
  Remark NVARCHAR(500), 
  Is_New_Student BIT DEFAULT(1) NOT NULL, 
  Is_Deactive BIT DEFAULT(0) NOT NULL,
  Is_RTE BIT DEFAULT(0) NOT NULL, 
  Apply_Concession BIT DEFAULT(0) NOT NULL, 
  Concession_Fee MONEY, 
  PreviousAcademicYearPendingFeeAmount MONEY,
  Academic_Year NVARCHAR(50),
  Do_you_required_parent_mobile_app_access BIT DEFAULT(0) NOT NULL,
  Mobile_Number_for_Application_Access VARCHAR(20),
  AppAccessOneTimePassword VARCHAR(1000),
  PasswordSalt VARCHAR(1000),
  Upassword VARCHAR(1000),

  Father_First_Name NVARCHAR(50), 
  Father_Middle_Name NVARCHAR(50), 
  Father_Last_Name NVARCHAR(50), 
  Father_Gender NVARCHAR(5), 
  Father_Mobile_No NVARCHAR(20), 
  Father_Alternate_Contact_No NVARCHAR(20), 
  Father_Email_Id VARCHAR(80), 
  Father_Address_Line_1 NVARCHAR(250), 
  Father_Address_Line_2 NVARCHAR(250), 
  Father_Country NVARCHAR(100), 
  Father_State NVARCHAR(100), 
  Father_District NVARCHAR(100), 
  Father_Taluka NVARCHAR(100), 
  Father_Pincode NVARCHAR(10), 
  Father_Adhaar_No NVARCHAR(20), 
  Father_Education NVARCHAR(50), 
  Father_Birth_Date DATETIME  NULL,  
  Father_Occupation NVARCHAR(50), 
  Father_Annual_Income MONEY, 
  Father_Blood_Group NVARCHAR(5), 

  Mother_First_Name NVARCHAR(50), 
  Mother_Middle_Name NVARCHAR(50), 
  Mother_Last_Name NVARCHAR(50), 
  Mother_Gender NVARCHAR(5), 
  Mother_Mobile_No NVARCHAR(20), 
  Mother_Alternate_Contact_No NVARCHAR(20), 
  Mother_Email_Id VARCHAR(80), 
  Mother_Address_Line_1 NVARCHAR(250), 
  Mother_Address_Line_2 NVARCHAR(250), 
  Mother_Country NVARCHAR(100), 
  Mother_State NVARCHAR(100), 
  Mother_District NVARCHAR(100), 
  Mother_Taluka NVARCHAR(100), 
  Mother_Pincode NVARCHAR(10), 
  Mother_Adhaar_No NVARCHAR(20), 
  Mother_Education NVARCHAR(50), 
  Mother_Birth_Date DATETIME  NULL,  
  Mother_Occupation NVARCHAR(50), 
  Mother_Annual_Income MONEY, 
  Mother_Blood_Group NVARCHAR(5), 

  Guardian_First_Name NVARCHAR(50), 
  Guardian_Middle_Name NVARCHAR(50), 
  Guardian_Last_Name NVARCHAR(50), 
  Guardian_Gender NVARCHAR(5), 
  Guardian_Mobile_No NVARCHAR(20), 
  Guardian_Alternate_Contact_No NVARCHAR(20), 
  Guardian_Email_Id VARCHAR(80), 
  Guardian_Address_Line_1 NVARCHAR(250), 
  Guardian_Address_Line_2 NVARCHAR(250), 
  Guardian_Country NVARCHAR(100), 
  Guardian_State NVARCHAR(100), 
  Guardian_District NVARCHAR(100), 
  Guardian_Taluka NVARCHAR(100), 
  Guardian_Pincode NVARCHAR(10), 
  Guardian_Adhaar_No NVARCHAR(20), 
  Guardian_Education NVARCHAR(50), 
  Guardian_Birth_Date DATETIME  NULL, 
  Guardian_Occupation NVARCHAR(50), 
  Guardian_Annual_Income MONEY, 
  Guardian_Blood_Group NVARCHAR(5) ,

  Current_CountryId INT,
  Current_StateId INT,
  Current_DistrictId INT,
  Current_TalukaId INT,

  Birth_CountryId INT,
  Birth_StateId INT, 
  Birth_DistrictId INT, 
  Birth_TalukaId INT,

  Father_CountryId INT NULL,
  Father_StateId INT NULL,
  Father_DistrictId INT NULL,
  Father_TalukaId INT NULL,

  Mother_CountryId INT NULL,
  Mother_StateId INT NULL,
  Mother_DistrictId INT NULL, 
  Mother_TalukaId INT NULL,

  Gaurdian_CountryId INT NULL,
  Gaurdian_StateId INT NULL, 
  Gaurdian_DistrictId INT NULL, 
  Gaurdian_TalukaId INT NULL
)
